version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-breed-app
    image: dog-breed
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - VITE_API_URL=https://dog.ceo/api/breed
      - VITE_SUPABASE_URL=https://zmwaeevxxhxnfahxfjbt.supabase.co
      - VITE_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptd2FlZXZ4eGh4bmZhaHhmamJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjYzNzIxNDYsImV4cCI6MTk4MTk0ODE0Nn0.Jffu5BwNIh2CHHEIST0YhHrJ3TKZhhYGulAzzEFYLHY
      - VITE_SUPABASE_PASS=senha-padrao
      - CHOKIDAR_USEPOLLING=true
