
version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-breed-app
    image: dog-breed
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - VITE_API_URL=https://dogbreed-api.q9.com.br
      - CHOKIDAR_USEPOLLING=true